### ISSUE TITLE
TypeError: Cannot read property 'subdomain' of undefined

### ISSUE THREAD

**Issue by eliotharper** [sfmc-developer-advocates/custom-activity-deskapi-node#1]
I get the following error in heroku logs or when running `node app.js` on localhost:

```
/app/routes/activityUtils.js:53
at Function.Module._load (module.js:312:12)
at require (module.js:380:17)
at Module.require (module.js:364:17)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
                                    ^
TypeError: Cannot read property 'subdomain' of undefined
exports.deskCreds.host = exports.deskCreds.subdomain + '.desk.com';
at Object.<anonymous> (/app/routes/activityUtils.js:53:43)
at Object.<anonymous> (/app/routes/index.js:4:21)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
Process exited with status 8
State changed from starting to crashed
```

Here's the fix. In `routes/activityUtils.js`, replace the last 3 lines with:

```
exports.deskCreds = {
  host: exports._deskCreds.subdomain + '.desk.com',
  supportEmail: 'support@' + exports._deskCreds.subdomain + '.desk-mail.com',
  token: new Buffer(exports._deskCreds.username + ':' + exports._deskCreds.userpw).toString('base64')
};
```

**Comment by timsim00** [comment]
I fixed this.  Thank you.
